version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: quiz-postgres
    environment:
      POSTGRES_DB: quiz_adaptativo
      POSTGRES_USER: quiz_user
      POSTGRES_PASSWORD: quiz_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: